In [2]:
# Create a 1D NumPy array with numbers from 1 to 10
import numpy as rr
a = rr.array([1,2,3,4,5,6,7,8,9])
print(f' 1D array {a}')
print(a.shape)

 1D array [1 2 3 4 5 6 7 8 9]
(9,)


In [11]:
# Create a NumPy array of zeros of size 5.
a = rr.zeros((5),dtype=int)
print(a)
print(a.shape)

[0 0 0 0 0]
(5,)


In [12]:
# Create a NumPy array of ones of size 4 × 4.
a = rr.ones((4,4),dtype=int)
print(a)
print(a.shape)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
(4, 4)


In [19]:
# Create an array of even numbers from 2 to 20.
even_number = rr.arange(21)
print(f' The Even numbers are {even_number[2:21:2]}')

 The Even numbers are [ 2  4  6  8 10 12 14 16 18 20]


In [16]:
# Create an array with values from 10 to 50, step 5.
value = rr.arange(10,50,5)
print(value)

[10 15 20 25 30 35 40 45]


In [21]:
# Create an array [1, 2, 3] and multiply it by 3.
multiply = rr.array([1,2,3])*3
print(multiply)

[3 6 9]


In [25]:
# Create two arrays and add them element-wise.
a = rr.array([1,2,3])
b = rr.array([4,5,6])
print('Sum : ',a+b)

Sum :  [5 7 9]


In [24]:
# Create an array [10, 20, 30, 40] and find its mean.
a = rr.array([10,20,30,40])
print(f' Mean : {a.mean()}')

 Mean : 25.0


In [29]:
# Create an array [4, 9, 16, 25] and find the square root.
square = rr.array([4,9,16,25])
print('Square root is ',rr.sqrt(square))

Square root is  [2. 3. 4. 5.]


In [32]:
# Create a random array of size 5 and find its sum.
abc = rr.random.random(5)
print ('Sum : ',abc.sum())

Sum :  2.3297249687515165


In [36]:
# Slice the first 5 elements from an array of numbers from 1 to 10.
Def = rr.array(rr.arange(1,10))
print(Def[:5])
print(Def[5:])

[1 2 3 4 5]
[6 7 8 9]


In [38]:
# Get the last two elements of [10, 20, 30, 40, 50].
hij = rr.array([10, 20, 30, 40, 50])
print(hij[3:])

[40 50]


In [39]:
# Change the 3rd element of [1, 2, 3, 4, 5] to 99.
abc = [1,2,3,4,5]
abc[2] = 99
print('Changed elemennt of abc : ',abc)

Changed elemennt of abc :  [1, 2, 99, 4, 5]


In [40]:
# Create a 3×3 matrix and access the element in the 2nd row, 3rd column.
abc = rr.array(rr.random.randint(5,30,(3,3)))
print(abc)

[[16 16 29]
 [ 5 10 28]
 [19 21  5]]


In [41]:
ijk = (2,3)
jk = rr.resize(abc,ijk)
print(jk)

[[16 16 29]
 [ 5 10 28]]


In [46]:
# Transpose a 2×3 matrix.
a = rr.array(rr.random.randint(1,10,(3,2)))
print(a)

[[3 2]
 [7 2]
 [2 4]]


In [47]:
print(a.transpose()) # 2 x 3

[[3 7 2]
 [2 2 4]]


In [50]:
# Create a 1D array and reverse it using slicing.
abc = rr.array(rr.arange(0,11))
print(abc)
print('Reverse : ',abc[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10]
Reverse :  [10  9  8  7  6  5  4  3  2  1  0]


In [55]:
# Generate a random integer between 1 and 100.
random_int = rr.array(rr.random.randint(1,100,(2,5)))
print('Random integer :',random_int)
print(random_int.shape)

Random integer : [[58  5 97 66 90]
 [20 12 74 64 36]]
(2, 5)


In [56]:
# Generate a random array of size 3 × 3.
random_array = rr.array(rr.random.randint(0,9,(3,3)))
print(random_array)

[[4 4 3]
 [4 3 4]
 [8 0 0]]


In [75]:
# Reshape a 1D array (1 to 12) into 3×4.
abc = rr.array(rr.arange(1,12))
print(abc)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [72]:
print('Reshape : ',abc.reshape(3,4))

Reshape :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
arr = rr.array(rr.random.random(5))
print(arr)

[0.08186279 0.52687371 0.29214962 0.79827387 0.10742251]


In [9]:
# normal distribution
arr = rr.random.normal(loc=0, scale = 1, size = 5)
print(arr)

[2.89700338 0.59436718 0.20593953 0.28139524 1.10902553]
