In [2]:
import numpy as np
a = np.array([2,3,4,5])
print(a)
print(type(a))

[2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
a.shape

(4,)

In [4]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [5]:
a = np.array([[[1,2,3],[4,5,6]],
              [[7,8,9],[1,2,3]]])
print(a)
a.shape

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


(2, 2, 3)

In [6]:
a = np.array(np.random.randint(1,20,size=(2,3,4,5)))
print(a)

[[[[11  3  4  2  7]
   [ 5 15 19  1  1]
   [ 8 15 19  4  8]
   [ 4  1  6 19  2]]

  [[ 7 18 10 15  3]
   [13  9 19 13  1]
   [10 19 19 10  2]
   [12 15  3 11 10]]

  [[10  8 15  1 13]
   [ 7  1  3 14 18]
   [ 3 15 14 17  5]
   [15 16  9 11 13]]]


 [[[11 18  3  3 13]
   [ 5  2 12 10 14]
   [ 1  8 15  2  6]
   [16  6 16 16  4]]

  [[ 4 16  9 19 15]
   [ 3  3  9 16  1]
   [17  8 15  4  1]
   [16 13 10 19  9]]

  [[ 8  9 13 11 15]
   [ 1 19  7  9 15]
   [ 6  3  6  6  1]
   [19  2  5  8 14]]]]


In [7]:
a_list = [1,2,3,4,5]
print(a_list*2)
a_array = np.array([1,2,3,4,5])
print(a_array*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [8]:
print(a_array.ndim)
print(a_array.size)

1
5


In [9]:
a.dtype

dtype('int32')

In [10]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
b = a.astype('float64')
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [11]:
import sys
# List
a = [1,2,3,4,5,6]
print(sys.getsizeof(a))
print(sys.getsizeof(a)*len(a))

104
624


In [12]:
# Array
a = np.array([1,2,3,4,5,6])
print(a.itemsize)
print(a.size*a.itemsize)

8
48


In [13]:
zero = np.zeros((3,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
ones = np.ones((3,4),dtype=int)
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
b = np.full((3,3),24)
b

array([[24, 24, 24],
       [24, 24, 24],
       [24, 24, 24]])

In [16]:
b = np.identity(4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
c = np.arange(7)
print(c)

[0 1 2 3 4 5 6]


In [18]:
list1 = [1,2,3,4,5,6]
converted = np.asarray(list1)
converted

array([1, 2, 3, 4, 5, 6])

In [19]:
a = np.arange(10)
print(a)
print(a[2:8])
print(a[::-1])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]
[9 8 7 6 5 4 3 2 1 0]


In [20]:
a = np.random.random(10)
a

array([9.88538289e-03, 1.35327897e-04, 3.87843124e-01, 8.86519588e-01,
       1.90591095e-01, 4.16244574e-01, 7.80753034e-02, 8.41754714e-01,
       9.52076148e-01, 8.54816455e-01])

In [21]:
a = np.random.randint(10,size=(1,4))
a

array([[1, 6, 4, 9]], dtype=int32)

In [22]:
arravali = np.array(np.random.randint(10,45,(8,2)))
print(arravali)
x = np.transpose(arravali)
print(x)

[[13 26]
 [33 32]
 [37 33]
 [28 18]
 [20 27]
 [32 38]
 [43 29]
 [24 35]]
[[13 33 37 28 20 32 43 24]
 [26 32 33 18 27 38 29 35]]


In [23]:
print(x.flatten())

[13 33 37 28 20 32 43 24 26 32 33 18 27 38 29 35]


In [24]:
x = np.array(np.random.randint(10,size=(2,5)))
print(x)

[[1 6 5 5 5]
 [2 4 7 0 1]]


In [25]:
print(x.reshape(5,2))

[[1 6]
 [5 5]
 [5 2]
 [4 7]
 [0 1]]


In [26]:
land = np.array(np.random.randint(10,size=(2,5)))
print(land)

[[7 3 2 3 1]
 [2 1 0 2 4]]


In [27]:
plant = (3,2,5)
b = np.resize(land,plant)
print(b)

[[[7 3 2 3 1]
  [2 1 0 2 4]]

 [[7 3 2 3 1]
  [2 1 0 2 4]]

 [[7 3 2 3 1]
  [2 1 0 2 4]]]


In [28]:
print(b.flatten())

[7 3 2 3 1 2 1 0 2 4 7 3 2 3 1 2 1 0 2 4 7 3 2 3 1 2 1 0 2 4]
