In [2]:
import numpy as np # first step
a = np.array([2,4,6,8,10])
print(a)
print(type(a))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


In [4]:
a.shape

(5,)

In [6]:
print(a,type(a),a.shape)

[ 2  4  6  8 10] <class 'numpy.ndarray'> (5,)


In [8]:
# 2D array
b = np.array([[1,2,3],[4,5,6]])
print(b,type(b),b.shape)

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3)


In [10]:
# 3D array
c = np.array([[[1,2,3],[4,5,6]],
             [[7,8,9],[10,11,12]]])
print(c,type(c),c.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] <class 'numpy.ndarray'> (2, 2, 3)


In [16]:
three_array = np.array([
   [
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
   ]
])
print(three_array)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [17]:
three_array.shape

(1, 3, 5)

In [21]:
# 4D array
four_array = np.random.randint(1,20, size=(2,3,4,5))
print(four_array)
print('Shape : ',four_array.shape)

[[[[15  5  3 19  7]
   [15  1  8 16 17]
   [ 2 10 17 17 13]
   [ 7 10  8 19 16]]

  [[17 17 15 15  7]
   [19 15  7  1 16]
   [ 4  5 11 11 10]
   [ 9 19  8  7  9]]

  [[18 11  5 17 11]
   [ 9 13 12 17 14]
   [ 8 16 14 16 11]
   [ 7  6 15  5 11]]]


 [[[19 12 13 17 19]
   [ 7 10 16  9  7]
   [ 8  7 17 16 16]
   [19 13  1 14  7]]

  [[ 9 19  6  9  8]
   [ 8  3  8 18 12]
   [ 2 12  8  9 17]
   [11  2 10  5  7]]

  [[ 5  7 17 13 10]
   [ 1  5  2 18  7]
   [15  8  6  6  4]
   [10 10 18  2  7]]]]
Shape :  (2, 3, 4, 5)


In [22]:
blocks = np.random.randint(1,50, size=(3,4,5,10))
print(blocks)
print('Shape : ',blocks.shape)

[[[[19 36 41 28 22 20 11 23 44 25]
   [49 22  2 44 39 11 38 19 24 34]
   [16 38  4 39 17 37 39 39 29 47]
   [43 48 32 29 38 11 23  6 36  5]
   [32 20 49 14 11 33 44  2 31 12]]

  [[ 2 43 45 29 23 33 33 45 16 21]
   [45 45  1 12 17 16 40 35 13  6]
   [33 23  2 16 12  1 27 49 39 14]
   [39 11 10 14 48 27 20 21 26 11]
   [39  6 49 46 25  3 29  7  8 43]]

  [[38 13 19 37 22 42 36 38 37 14]
   [23 15  3 33  1 29 46 16 36 34]
   [ 5 25 29  6  5 44 27 33 33 24]
   [13 46 25 45 24 42 28 39 46 24]
   [21  7 27 43 28 48 27 17 20 46]]

  [[16 46 35  6 19 27 28 25 39 15]
   [26 19 10 34 23 28 23  6 38 15]
   [33 17 12  4 36 31 33  5 28  6]
   [47 35 26 25 11 46 46  3 18 33]
   [19 29 10 22  5  5 33 12 41 21]]]


 [[[39 17 12 43 27 16 25 15 15 35]
   [ 9 17 39 43 32 10  8 37 47 11]
   [14 37 26 46 45  5 48 36 13 33]
   [43 16 14 33 41 26 28  6 49  5]
   [ 9 47 45 22 32 18 13 31 38 35]]

  [[23 48 10  9 31 49 25 25 38 17]
   [24 20 14  8 38 47 21  6 33 38]
   [46 12 13  8 16 48 20 41 32 25]
   [23  

In [6]:
c = np.random.randint(1,5,size=(1,3,5))
print(c)
c.shape

[[[1 3 3 2 3]
  [3 3 1 3 4]
  [1 3 1 2 1]]]


(1, 3, 5)

In [25]:
# List vs Array
a_list = [1,2,3,4,5]
print(a_list*2)
a_array = np.array( [1,2,3,4,5])
print(a_array*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [34]:
b = [1,2,3,4,5,6,7,8,9,10]
print(b*2)
b_array = np.array(b)
print(b_array*2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 2  4  6  8 10 12 14 16 18 20]


In [38]:
# ndarray.ndim
a = np.array([0,1,2,3,4,5,6,7,8,9,10])
print('Dimensions of a : ',a.ndim)
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Dimensions of b : ',b.ndim)
c = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
print('Dimension of c : ',c.ndim)

Dimensions of a :  1
Dimensions of b :  2
Dimension of c :  3


In [39]:
# ndarray.size
a = np.array([0,1,2,3,4,5,6,7,8,9,10])
print('Dimensions of a : ',a.size)
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Dimensions of b : ',b.size)
c = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
print('Dimension of c : ',c.size)

Dimensions of a :  11
Dimensions of b :  10
Dimension of c :  9


In [41]:
# ndarray.dtype
a = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(a.dtype)

int64


In [42]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b.dtype)

int64


In [43]:
c = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
print(c.dtype)

int64


In [45]:
d = np.array([0,1,2,3,4,5,6,7,8,9,10,'abc'])
print(d.dtype)

<U21


In [8]:
# ndarray.astype
a = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(a)
print(a.dtype)

a_type = a.astype('float64')
print(a_type)
print(a_type.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10]
int64
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
float64


In [51]:
# Memory
import numpy as np
import sys
# declaring a list of 10 elements
a = [0,1,2,3,4,5,6,7,8,9,10] # list
print('Size of each element of list in bytes : ',sys.getsizeof(a))
print('Size of whole elements of list in bytes : ',sys.getsizeof(a)*len(a))
# declaring a array of 10 elements
a_array = np.array([0,1,2,3,4,5,6,7,8,9,10])
print('Size of each element of array in bytes : ',a_array.itemsize)
print('Size of whole elements of array in bytes : ',a_array.size*a_array.itemsize)

Size of each element of list in bytes :  152
Size of whole elements of list in bytes :  1672
Size of each element of array in bytes :  8
Size of whole elements of array in bytes :  88


In [54]:
# Performance
import numpy as ab
import time
size = 10000 # size and list
# declaring list
list1 = range(size)
list2 = range(size)
# declaring array
array1 = ab.arange(size)
array2 = ab.arange(size)

# capturing time before the multiplication of python lists
initialTime = time.time()

# multiplying elements of both the lists and stored in another list
resultantList = [(a*b) for a,b in zip(list1,list2)]

# Calculating execution time
print('Time taken by lists to perform multiplication : ',(time.time()-initialTime),'Seconds')

# capturing time before the multiplication of Numpy arrays
initialTime = time.time()

# multiplying elements of both the Numpy arrays and stored in another Numpy array
resultantArray = array1*array2

# calculating execution time
print('Time taken by Numpy Arrays to perform multiplication : ',(time.time()-initialTime),'Seconds')

Time taken by lists to perform multiplication :  0.0020575523376464844 Seconds
Time taken by Numpy Arrays to perform multiplication :  0.00010967254638671875 Seconds


In [66]:
# Initialized
import numpy as np
zero_array = np.zeros((3,3))
another_zero_array = np.zeros((4,3),dtype=int)
print(zero_array)
print(another_zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [67]:
ones_array = np.ones((3,3))
another_ones_array = np.ones((4,3),dtype=int)
print(ones_array)
print(another_ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [68]:
a = np.full((3,3),30)
print(a)

[[30 30 30]
 [30 30 30]
 [30 30 30]]


In [69]:
a = np.identity(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [78]:
# Array from numerical ranges
array_with_range = np.arange(7)
print(array_with_range)

[0 1 2 3 4 5 6]


In [79]:
array_with_range = np.arange(10,20,2)
print(array_with_range)

[10 12 14 16 18]


In [85]:
array_range = np.arange(10)
print(array_range)

[0 1 2 3 4 5 6 7 8 9]


In [89]:
array_range = np.arange(5,105,5)
print(array_range)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [3]:
# Creating ndarray 
# convert list into array
array_list = [1,2,3,4,5]
convert_list_array = np.asarray(array_list)
print('List converted into Array : ',convert_list_array,'Shapes : ',convert_list_array.shape)

List converted into Array :  [1 2 3 4 5] Shapes :  (5,)


In [96]:
# convert tuple into array
array_tuple = (1,2,3,4,5)
convert_tuple_array = np.asarray(array_tuple)
print('Tuple converted into Array : ',convert_tuple_array,'Shapes : ',convert_tuple_array.shape)

Tuple converted into Array :  [1 2 3 4 5] Shapes :  (5,)


In [101]:
# Output
print('List converted into Array : ',convert_list_array,'Shapes : ',convert_list_array.shape)
print('Tuple converted into Array : ',convert_tuple_array,'Shapes : ',convert_tuple_array.shape)

List converted into Array :  [1 2 3 4 5] Shapes :  (5,)
Tuple converted into Array :  [1 2 3 4 5] Shapes :  (5,)


In [113]:
a = np.arange(10)
print(a)
print(a[2:9])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8]


In [121]:
a = np.random.random(10) # range 0 to 1
print(a)

[0.34732429 0.38041604 0.39270227 0.94404438 0.58522352 0.43046205
 0.54805702 0.49863859 0.31115125 0.04414498]


In [124]:
print(a[::2])

[0.34732429 0.39270227 0.58522352 0.54805702 0.31115125]


In [9]:
# 2-D Array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Array : ',a)
print('Shape :' ,a.shape)
print(a[0,1])
print(a[0,0])
print(a[0:2])
print(a[0:1,-1:])

Array :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape : (3, 3)
2
1
[[1 2 3]
 [4 5 6]]
[[3]]


In [134]:
a = np.array([[[1,2],[3,4],[5,6]],
              [[7,8],[9,10],[11,12]],
              [[13,14],[15,16],[17,18]]])
print('Array : ',a)
print('Shapes : ',a.shape)
print('Slicing : ',a[0:2])
print(a[0:2,1])
print(a[0:2,1:])
print(a[0:2,1:,1])
print(a[0:2,1:,1:])

Array :  [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
Shapes :  (3, 3, 2)
Slicing :  [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[ 3  4]
 [ 9 10]]
[[[ 3  4]
  [ 5  6]]

 [[ 9 10]
  [11 12]]]
[[ 4  6]
 [10 12]]
[[[ 4]
  [ 6]]

 [[10]
  [12]]]


In [135]:
b = np.array([[[1,10],[2,20],[3,30]],
              [[4,40],[5,50],[6,60]],
              [[7,70],[8,80],[9,90]]])
print(b)
print(b.shape)


[[[ 1 10]
  [ 2 20]
  [ 3 30]]

 [[ 4 40]
  [ 5 50]
  [ 6 60]]

 [[ 7 70]
  [ 8 80]
  [ 9 90]]]
(3, 3, 2)


In [141]:
print(b[0,0],b[0,1],b[0,2])

[ 1 10] [ 2 20] [ 3 30]


In [144]:
print(b[0:2,1])

[[ 2 20]
 [ 5 50]]


In [10]:
# Transpose
# Create a 2 D array 
arravali = np.array(np.random.randint(10,45,(8,2)))
print(f'The defined array is \n {arravali}')
print(f'The defined array is \n {arravali.shape}')

The defined array is 
 [[12 39]
 [26 27]
 [27 24]
 [43 17]
 [16 34]
 [16 22]
 [28 34]
 [36 19]]
The defined array is 
 (8, 2)


In [12]:
x = np.transpose(arravali)
print(x)
print(x.shape)

[[12 26 27 43 16 16 28 36]
 [39 27 24 17 34 22 34 19]]
(2, 8)


In [15]:
a = np.array(np.random.randint(5,25,(2,6,3)))
print(a)
print(a.shape)

[[[ 6  6 23]
  [12 20 24]
  [19 15 13]
  [ 5  5 11]
  [22 10  9]
  [23 10 21]]

 [[ 5 11 16]
  [12 10 19]
  [24  9 23]
  [15 14 10]
  [13  6 14]
  [ 6 10  7]]]
(2, 6, 3)


In [16]:
b = np.transpose(a)
print(b)
print(b.shape)

[[[ 6  5]
  [12 12]
  [19 24]
  [ 5 15]
  [22 13]
  [23  6]]

 [[ 6 11]
  [20 10]
  [15  9]
  [ 5 14]
  [10  6]
  [10 10]]

 [[23 16]
  [24 19]
  [13 23]
  [11 10]
  [ 9 14]
  [21  7]]]
(3, 6, 2)


In [21]:
Lr = np.array(np.random.randint(5,25,(4,2)))
print(Lr)
print(Lr.shape)

[[24 21]
 [20 21]
 [20 21]
 [13 10]]
(4, 2)


In [22]:
Rr = (2,2,2)
a = np.reshape(Lr,Rr)
print(a)

[[[24 21]
  [20 21]]

 [[20 21]
  [13 10]]]


In [24]:
vi = np.array(np.random.randint(5,35,(2,3,2)))
print(vi)
print(vi.shape)

[[[27 19]
  [ 5 30]
  [28 15]]

 [[12 16]
  [10 32]
  [34 20]]]
(2, 3, 2)


In [31]:
Li = (3,2,2)
shape = np.reshape(vi,Li)
print(shape)
print(f'\n {shape.shape}')

[[[27 19]
  [ 5 30]]

 [[28 15]
  [12 16]]

 [[10 32]
  [34 20]]]

 (3, 2, 2)


In [36]:
# resize
land = np.array(np.random.randint(5,105,(3,2,8))) # Total elements is 48
print(land)

[[[ 63  32  80  43  37  26  98  67]
  [ 95  45  67  93  64  94  72  75]]

 [[ 87  71 100  71  43  47  27  38]
  [ 65  58  31  96  76  10  15  21]]

 [[ 54  51  42  62  56  26 103  91]
  [ 20  42  24  54  42  88  49  94]]]


In [37]:
plant = (5,2,10) # here the total elements is 100
building = np.resize(land,plant)
print(building)

[[[ 63  32  80  43  37  26  98  67  95  45]
  [ 67  93  64  94  72  75  87  71 100  71]]

 [[ 43  47  27  38  65  58  31  96  76  10]
  [ 15  21  54  51  42  62  56  26 103  91]]

 [[ 20  42  24  54  42  88  49  94  63  32]
  [ 80  43  37  26  98  67  95  45  67  93]]

 [[ 64  94  72  75  87  71 100  71  43  47]
  [ 27  38  65  58  31  96  76  10  15  21]]

 [[ 54  51  42  62  56  26 103  91  20  42]
  [ 24  54  42  88  49  94  63  32  80  43]]]


In [39]:
# flatten
land = np.array(np.random.randint(5,105,(5,2,10)))
print(land)

[[[ 79  98  62  60 101  53  45  17  28  28]
  [ 49  24  93  96  59  41  42  91  40  81]]

 [[ 27  51  75  21  26  13  34  96  62  21]
  [ 83  83  48  68  71  41  98  27  84  84]]

 [[ 97  19  64  99  89  11  28  67  55  30]
  [  5  90  30  20  27  60  74  88  30  76]]

 [[ 80  51 102  60  77  67  15  98  28  90]
  [ 34  13  77  33 101  69  57  43  19  21]]

 [[ 24  75  35  65  56  36 102  78  91  77]
  [ 26  43  89  83 100  79   6  21  84  31]]]


In [43]:
land.flatten()

array([ 79,  98,  62,  60, 101,  53,  45,  17,  28,  28,  49,  24,  93,
        96,  59,  41,  42,  91,  40,  81,  27,  51,  75,  21,  26,  13,
        34,  96,  62,  21,  83,  83,  48,  68,  71,  41,  98,  27,  84,
        84,  97,  19,  64,  99,  89,  11,  28,  67,  55,  30,   5,  90,
        30,  20,  27,  60,  74,  88,  30,  76,  80,  51, 102,  60,  77,
        67,  15,  98,  28,  90,  34,  13,  77,  33, 101,  69,  57,  43,
        19,  21,  24,  75,  35,  65,  56,  36, 102,  78,  91,  77,  26,
        43,  89,  83, 100,  79,   6,  21,  84,  31], dtype=int32)

In [45]:
print(shape.flatten())

[27 19  5 30 28 15 12 16 10 32 34 20]


In [ ]:
a = np.array(np.random.randi)