In [2]:
# Numpy
import numpy as ak
numbers = ak.array(ak.arange(1,11))
print(numbers)
print(numbers.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [5]:
zero = ak.zeros(5,dtype=int)
print(zero)

[0 0 0 0 0]


In [13]:
number = ak.ones((4,4),dtype=int)
print(number)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [18]:
even_number = ak.arange(21)
print(f'even_numbers are {even_number[2:21:2]}')

even_numbers are [ 2  4  6  8 10 12 14 16 18 20]


In [21]:
values = ak.arange(5,50,5)
print(f' Array values of 5 steps : {values}')

 Array values of 5 steps : [ 5 10 15 20 25 30 35 40 45]


In [23]:
multiply = ak.array([1,2,3])*3
print(f'Multiply the 1,2,3 with 3 is the answer is {multiply}')

Multiply the 1,2,3 with 3 is the answer is [3 6 9]


In [24]:
a = ak.array([10,20,30])
b = ak.array([40,50,60])
print('Sum : ',a+b)

Sum :  [50 70 90]


In [29]:
a = ak.array([10,20,30,40])
print(a.mean())

25.0


In [30]:
b = ak.array([4,9,16,25])
print(ak.sqrt(b))

[2. 3. 4. 5.]


In [32]:
c = ak.array(ak.random.random(5))
print('Sum : ',ak.sum(c))

Sum :  2.211407175227124


In [34]:
abc = ak.array(ak.arange(1,10))
print('First 5 element : ',abc[:5])

First 5 element :  [1 2 3 4 5]


In [36]:
abc = ak.array([10,20,30,40,50])
print('Last two elements : ',abc[3:])

Last two elements :  [40 50]


In [38]:
xyz = ak.array([1,2,3,4,5])
xyz[2] = 99
print('The 3rd element is changed as : ',xyz)

The 3rd element is changed as :  [ 1  2 99  4  5]


In [39]:
xyz = ak.array(ak.random.randint(5,30,(3,3)))
print(xyz)

[[ 8 21 26]
 [14  7 16]
 [28 18 18]]


In [40]:
xyz.resize(2,3)
print(xyz)

[[ 8 21 26]
 [14  7 16]]


In [41]:
kj = ak.array([10,20,30,40,50])
print(f' Reverse {kj[::-1]}')

 Reverse [50 40 30 20 10]


In [49]:
jk = ak.array(ak.random.randint(1,100,(5,)))
print(jk)

[ 6 48 56 34 42]


In [53]:
ji = ak.array(ak.random.randint(1,25,(3,3)))
print(ji)

[[ 3 14  4]
 [16 19 14]
 [22 19  6]]


In [77]:
ji = ak.array(ak.random.randint(5))
print(ji)

1


In [4]:
gk = ak.array(ak.random.random(10))
print(gk)

[0.79802481 0.02267241 0.92920355 0.0958657  0.006762   0.89499388
 0.45102849 0.61287901 0.43322264 0.33112964]


In [94]:
abc = ak.array(ak.random.randint(1,25,(3,2)))
print(abc)

[[12  4]
 [ 9 22]
 [23 13]]


In [95]:
print(abc.transpose())

[[12  9 23]
 [ 4 22 13]]


In [96]:
abc = ak.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(abc)
print(abc.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [98]:
print(abc.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [99]:
print(abc.reshape(6,2))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [101]:
print(abc.reshape(1,12))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [102]:
abc = ak.array(ak.random.randint(1,11,(5,2)))
print(abc)

[[1 7]
 [9 3]
 [4 8]
 [2 1]
 [1 9]]


In [108]:
print(abc.flatten())

[1 7 9 3 4]


In [116]:
arr = ak.random.uniform(0,1,10)
print(arr)

[0.45055841 0.52254116 0.14133403 0.39132041 0.25866844 0.02016011
 0.02813822 0.64354152 0.83125704 0.89061164]


In [127]:
arr = ak.random.rand(10)*1
print(arr)

[0.48887018 0.75584154 0.19127499 0.3507648  0.03035833 0.79791612
 0.73434748 0.12960757 0.22423501 0.1528964 ]


In [133]:
abc = ak.array([1,2,3,4,5])
ak.random.shuffle(abc)
print(abc)

[3 2 1 5 4]


In [135]:
abcd = ak.array([1,2,3,4,5])
print(abcd,abcd.shape)

[1 2 3 4 5] (5,)


In [154]:
abc_repeat = ak.tile(abcd,2)[:9]
print(abc_repeat)

[1 2 3 4 5 1 2 3 4]


In [157]:
print(abc_repeat.reshape(3,3))


[[1 2 3]
 [4 5 1]
 [2 3 4]]


In [161]:
zeo = ak.pad(abcd,(0,9))
print(zeo)

[1 2 3 4 5 0 0 0 0 0 0 0 0 0]


In [165]:
print(zeo.reshape(3,4))

[[1 2 3 4]
 [5 0 0 0]
 [0 0 0 0]]


In [180]:
defg = ak.array(ak.random.randint(1,8,(5,)))
print(defg)

[7 2 7 4 3]


In [181]:
abc = ak.tile(defg,3)[:10]
print(abc)
print(abc.reshape(2,5))

[7 2 7 4 3 7 2 7 4 3]
[[7 2 7 4 3]
 [7 2 7 4 3]]


In [188]:
jio = ak.pad(defg,(0,15))
print(jio)
print(jio.reshape(2,2,5))

[7 2 7 4 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[[7 2 7 4 3]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]]]


In [6]:
# Aggregate function
import numpy as np
a = np.array([[1,2],[3,4]]) # [1,2]
print(np.sum(a))             # [3,4]
print(np.mean(a))
print(np.min(a))
print(np.max(a))
print(np.std(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

10
2.5
1
4
1.118033988749895
[4 6]
[3 7]
