In [34]:
import numpy as li
a = li.random.rand(4,3) # I given here 4 show it shows 4 array randomly.
print(a)

[[0.38995758 0.75613605 0.78458926]
 [0.10412273 0.8935025  0.1572973 ]
 [0.39077706 0.36778629 0.69639038]
 [0.06224901 0.40065821 0.24329428]]


In [35]:
a = li.random.randn(6,1)
print(a)

[[ 0.73912232]
 [ 0.74997375]
 [-0.79764985]
 [-0.54024181]
 [ 1.53112308]
 [ 0.18224755]]


In [36]:
a = li.random.randint(1,10)
print(a)

9


In [37]:
a = li.array(li.random.randint(1,10,(5,2)))
a.sum(axis=0)
a.sum(axis=1)

array([ 6, 12,  9,  8, 11])

In [39]:
a.sum(axis=1)

array([ 6, 12,  9,  8, 11])

In [45]:
a = ([10,20,30,40,50,60,70,80])
a[0],a[1],a[2]

(10, 20, 30)

In [46]:
a = (['apple','banana'])
a[0],a[1][2]

('apple', 'n')

In [49]:
a = li.array(li.random.randint(5,10,(2,5)))
print(a)

[[7 7 8 5 9]
 [7 6 8 7 7]]


In [50]:
a.flatten()

array([7, 7, 8, 5, 9, 7, 6, 8, 7, 7], dtype=int32)

In [51]:
print(a.ravel())

[7 7 8 5 9 7 6 8 7 7]


In [52]:
print(a.flatten())

[7 7 8 5 9 7 6 8 7 7]


In [53]:
a = li.full((2,2),8)
print(a)

[[8 8]
 [8 8]]
